import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import { Geist, Geist_Mono } from "next/font/google";

import "./globals.css";
import { FilterProvider } from "@/context/FilterContext";
import { FavoritesProvider } from "@/context/FavoritesContext";
import Player from "@/components/player";
import Navbar from "@/components/navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "RandomFM",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col bg-background text-foreground">
        <ClerkProvider>
          <FavoritesProvider>
            <FilterProvider>
              <header className="flex border-b border-border">
                <Navbar />
              </header>
              <main className="mx-auto flex w-full max-w-6xl flex-1 flex-col px-4 py-8">
                {children}
              </main>
              <Player />
            </FilterProvider>
          </FavoritesProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}
