import type { Metadata } from "next";
import {
  ClerkProvider,
  Show,
  SignOutButton,
  SignUpButton,
  UserButton,
} from "@clerk/nextjs";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Logo from "next/image";
import Player from "@/components/player";
import { FilterProvider } from "@/context/FilterContext";
import Link from "next/link";
import { LikedStationsLink } from "@/components/liked-stations-link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "RandomFM",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col bg-background text-foreground">
        <ClerkProvider>
          <FilterProvider>
            <header className="flex border-b border-border">
              <div className="mx-auto flex h-16 w-full max-w-6xl items-center justify-between px-4">
                <Link
                  href="/"
                  className="flex items-center gap-4 text-xl text-foreground font-bold tracking-wide"
                >
                  <Logo
                    src="/random-fm-logo.svg"
                    alt="RandomFM-Logo"
                    width={25}
                    height={25}
                    className="h-6 w-auto"
                  />
                  RandomFM
                </Link>
                <div className="flex items-center justify-between gap-4">
                  <Link href="/about" className="text-white">
                    About
                  </Link>
                  <LikedStationsLink />
                  <Show when="signed-out">
                    <SignUpButton mode="modal">
                      <button className="bg-foreground text-background rounded-full font-medium text-sm sm:text-base h-10 px-8 cursor-pointer">
                        Sign Up
                      </button>
                    </SignUpButton>
                  </Show>
                  <Show when="signed-in">
                    <SignOutButton>
                      <button className="bg-foreground text-background rounded-full font-medium text-sm sm:text-base h-10 px-8 cursor-pointer">
                        Sign Out
                      </button>
                    </SignOutButton>
                  </Show>
                </div>
              </div>
            </header>
            <main className="mx-auto flex w-full max-w-6xl flex-1 flex-col px-4 py-8">
              {children}
            </main>
            <Player />
          </FilterProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}
